### PR TITLE
Python 3.10 support

### PR DESCRIPTION
**Pull request by gopiotr**
Built and tested using zephyr menuconfig against Python 3.10 on Windows 10 using Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30705 for x64.

Moreover PDCurses was updated to the newest available version on [2e15c90 commit](https://github.com/wmcbrine/PDCurses/tree/2e15c90f122fef329b83a4c3c011f192d97ec516).

Release version was changed from 2.2.0 to 2.3.0.

Fixes https://github.com/zephyrproject-rtos/windows-curses/issues/26 and https://github.com/zephyrproject-rtos/windows-curses/issues/27

### CODE REVIEW

**Comment by gopiotr** [comment]
@carlescufi @tejlmand @mbolivar-nordic @MartyMacGyver could you look at this and make review?

**Comment by MartyMacGyver** [comment]
Below are the diffs for the two Python modules that were brought in from Python's 3.10 branch:

-----
This first diff is based on https://github.com/python/cpython/commits/v3.10.0/Modules/_cursesmodule.c

```
 py310/_cursesmodule.c | 37 ++++++++++++++++++++++++++++++++++---
 1 file changed, 34 insertions(+), 3 deletions(-)

diff --git a/py310/_cursesmodule.c b/py310/_cursesmodule.c
index 511073f..4437114 100644
--- a/py310/_cursesmodule.c
+++ b/py310/_cursesmodule.c
@@ -103,13 +103,22 @@ static const char PyCursesVersion[] = "2.2";
 #define PY_SSIZE_T_CLEAN
 
 #include "Python.h"
-#include "pycore_long.h"          // _PyLong_GetZero()
-#include "pycore_structseq.h"     // PyStructSequence_InitType()
+
+/* This function declaration was moved from pycore_structseq.h file to adapt
+it for windows-curses package */
+PyAPI_FUNC(int) _PyStructSequence_InitType(
+    PyTypeObject *type,
+    PyStructSequence_Desc *desc,
+    unsigned long tp_flags);
 
 #ifdef __hpux
 #define STRICT_SYSV_CURSES
 #endif
 
+#ifdef _WIN32
+#include <windows.h>
+#endif
+
 #define CURSES_MODULE
 #include "py_curses.h"
 
@@ -1407,6 +1416,12 @@ _curses_window_getch_impl(PyCursesWindowObject *self, int group_right_1,
     else {
         rtn = mvwgetch(self->win, y, x);
     }
+
+    // windows-curses hack to make resizing work the same as in ncurses.  See
+    // PDCurses' documentation for resize_term().
+    if (rtn == KEY_RESIZE)
+        resize_term(0, 0);
+
     Py_END_ALLOW_THREADS
 
     return rtn;
@@ -1444,6 +1459,12 @@ _curses_window_getkey_impl(PyCursesWindowObject *self, int group_right_1,
     else {
         rtn = mvwgetch(self->win, y, x);
     }
+
+    // windows-curses hack to make resizing work the same as in ncurses.  See
+    // PDCurses' documentation for resize_term().
+    if (rtn == KEY_RESIZE)
+        resize_term(0, 0);
+
     Py_END_ALLOW_THREADS
 
     if (rtn == ERR) {
@@ -1511,8 +1532,14 @@ _curses_window_get_wch_impl(PyCursesWindowObject *self, int group_right_1,
         PyErr_SetString(PyCursesError, "no input");
         return NULL;
     }
-    if (ct == KEY_CODE_YES)
+    if (ct == KEY_CODE_YES) {
+        // windows-curses hack to make resizing work the same as in ncurses.  See
+        // PDCurses' documentation for resize_term().
+        if (rtn == KEY_RESIZE)
+            resize_term(0, 0);
+
         return PyLong_FromLong(rtn);
+    }
     else
         return PyUnicode_FromOrdinal(rtn);
 }
@@ -3368,7 +3395,9 @@ static PyObject *
 _curses_setupterm_impl(PyObject *module, const char *term, int fd)
 /*[clinic end generated code: output=4584e587350f2848 input=4511472766af0c12]*/
 {
+#ifndef _WIN32
     int err;
+#endif
 
     if (fd == -1) {
         PyObject* sys_stdout;
@@ -3389,6 +3418,7 @@ _curses_setupterm_impl(PyObject *module, const char *term, int fd)
         }
     }
 
+#ifndef _WIN32
     if (!initialised_setupterm && setupterm((char *)term, fd, &err) == ERR) {
         const char* s = "setupterm: unknown error";
 
@@ -3401,6 +3431,7 @@ _curses_setupterm_impl(PyObject *module, const char *term, int fd)
         PyErr_SetString(PyCursesError,s);
         return NULL;
     }
+#endif
 
     initialised_setupterm = TRUE;
 
```

-----

This diff is based on https://github.com/python/cpython/commits/v3.10.0/Modules/clinic/_cursesmodule.c.h

```
 py310/clinic/_cursesmodule.c.h | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/py310/clinic/_cursesmodule.c.h b/py310/clinic/_cursesmodule.c.h
index 9c96116..f5e3eba 100644
--- a/py310/clinic/_cursesmodule.c.h
+++ b/py310/clinic/_cursesmodule.c.h
@@ -509,8 +509,12 @@ _curses_window_box(PyCursesWindowObject *self, PyObject *args)
 {
     PyObject *return_value = NULL;
     int group_right_1 = 0;
-    PyObject *verch = _PyLong_GetZero();
-    PyObject *horch = _PyLong_GetZero();
+
+    /* Private function _PyLong_GetZero from pycore_long.h file was replaced
+    by public function PyLong_FromLong function to adapt it for
+    windows-curses package */
+    PyObject *verch = PyLong_FromLong(0);
+    PyObject *horch = PyLong_FromLong(0);
 
     switch (PyTuple_GET_SIZE(args)) {
         case 0:
```

**Comment by MartyMacGyver** [comment]
I'm able to build the wheel for this successfully using the method I've mentioned elsewhere:

Open "x64 Native Tools Command Prompt for VS 2017/2019/2022"

    cd /d \YOUR\PATH\TO\THE\REPO\windows-curses
    git submodule update --init
    build-wheels.bat 3.10

The install step seems to go fine:
    py -3.10 -m pip install dist\windows_curses-2.3.0-cp310-cp310-win_amd64.whl

**Review by mbolivar-nordic — APPROVED** [review]
No objections, thanks for taking this on @gopiotr

**Comment by MartyMacGyver** [comment]
I've tried this with the scripts in the examples folder using windows-curses 2.2.0 on Python 3.9, and this new 2.3.0 version on Python 3.10. I'm curious if there is any other functionality unique to this repo that ought to be tried out because so far the examples all seem to work equally well with the new 3.10 build.

**Comment by gopiotr** [comment]
> I've tried this with the scripts in the examples folder using windows-curses 2.2.0 on Python 3.9, and this new 2.3.0 version on Python 3.10. I'm curious if there is any other functionality unique to this repo that ought to be tried out because so far the examples all seem to work equally well with the new 3.10 build.

So if I compare `_cursesmodule.c` file from py39 and py310, the main difference is that in newer version was added color handling (new functions `color_allow_default_converter`, `color_converter`, `pair_converter` and `component_converter`). I do not know how they can be tested more precisely. `windows-curses` repository is a part of `zephyrproject-rtos` and  it is used there to enable using `menuconfig` on Windows OS, so I was focused mostly to test it there. But if you or anybody else have idea how to test it better I am open to propositions (or test results) :)

**Comment by mbolivar-nordic** [comment]
> `windows-curses` repository is a part of `zephyrproject-rtos` and it is used there to enable using `menuconfig` on Windows OS, so I was focused mostly to test it there

From my perspective, any additional testing suggestions or reports are very welcome, but we should not block the merge on waiting for these. This package is something that zephyr uses for `menuconfig`. If other people find it useful for other things, that's great. But we make no guarantees about that: `menuconfig` is the only thing we need it for.

**Comment by MartyMacGyver** [comment]
@gopiotr @mbolivar-nordic If this is working fine with `menuconfig` as well then by all means, let's get this merged and published to Pypi!

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
