### PR TITLE
Python 3.11 support

### PR DESCRIPTION
**Pull request by changyuheng**
Fixes https://github.com/zephyrproject-rtos/windows-curses/issues/31

### CODE REVIEW

**Review by liuyangzys — APPROVED** [review]

**Comment by pierreluctg** [comment]
Is there anything preventing this from being merged and released?

**Comment by stephanosio** [comment]
Rebased

**Review by stephanosio — COMMENTED** [review]
The PDCurses submodule update [from 2e15c90f122fef329b83a4c3c011f192d97ec516 to 2fa0f10dd844da47ee83c05a40a1ec541ceb95e1](https://github.com/zephyrproject-rtos/PDCurses/compare/2e15c90f122fef329b83a4c3c011f192d97ec516...2fa0f10dd844da47ee83c05a40a1ec541ceb95e1) seems unrelated to adding Python 3.11 support.

Unless it is actually needed, please remove it (or open a separate PR for it).

**Comment by stephanosio** [comment]
@changyuheng I have reworked this PR to exclude the PDCurses update. Please open another pull request if you require this update.

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
