### PR TITLE
Add support for Python 3.12 and bump to 2.3.2

### LINKED ISSUE #45: Add support for Python 3.12
Hello, 

Python 3.12 (final) has officially released.
Could you please add support for Python 3.12?

The fact is that I use a nvitop (https://github.com/XuehaiPan/nvitop) app that is actively supporting.
It depends on curses (with libncursesw). So, I cannot install the nvitop in Windows under Python 3.12 on the following error:

`ERROR: Cannot install nvitop==0.10.0, nvitop==0.10.1, nvitop==0.10.2, nvitop==0.11.0, nvitop==0.9.0, nvitop==1.0.0, nvitop==1.1.1, nvitop==1.1.2, nvitop==1.2.0, nvitop==1.3.0 and nvitop==1.3.1 because these package versions have conflicting dependencies.`

`The conflict is caused by:`
    `nvitop 1.3.1 depends on windows-curses>=2.2.0; platform_system == "Windows"`
    `nvitop 1.3.0 depends on windows-curses>=2.2.0; platform_system == "Windows"`
    `etc`

### PR DESCRIPTION
**Pull request by gschizas**
Simple version bump and support for Python 3.12

Fixes #45

### CODE REVIEW

**Comment by carlescufi** [comment]
@gschizas thank you very much for the PR!

**Comment by carlescufi** [comment]
@stephanosio something is broken in CI with Python 3.10 and higher FYI.

**Comment by alexrashed** [comment]
Hi @gschizas & @carlescufi!
I would love to see this being merged / the issue being fixed, which is why I stumbled upon this PR. 🚀
I looked at the CI issue in a fork, and it seems that the windows-2022 github runner images have been updated and the referenced toolset version is not present on the machines anymore. The latest version present on the runner images (according to [the runner docs](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md)) is 14.37.
So changing the toolset version for all matrix variants which use the windows-2022 runner to this version should fix the CI.
In fact, I tested this in my fork and it worked on first try: https://github.com/alexrashed/windows-curses/actions/runs/6562848823
Here's the commit I tested: https://github.com/zephyrproject-rtos/windows-curses/commit/ecc240511a803d8c10d90cc243b87c579e9ecff3
Considering that this repo isn't maintained too well, I think it would be easier to just integrate this in your changeset (instead of me filing a PR, waiting for a merge, then rebasing and adjusting yours afterwards).
Please let me know if I can help somehow to get this over the line!

**Comment by giorgosioak** [comment]
Hi everyone,

I can confirm the change that @alexrashed suggested is working and i was able to build properly for python 3.10 and 3.11 plus the 3.12 with by updating the workflow

I have made a commit https://github.com/giorgosioak/windows-curses/commit/673d11f185f381757316370b0396c2170fff182e 

Build details and artifacts from my build can be found here: https://github.com/giorgosioak/windows-curses/actions/runs/6593735175

**Comment by carlescufi** [comment]
@giorgosioak thank you for the patch
@gschizas can you please rebase this PR so that it only contains the two relevant commits and no merge commits please?

@alexrashed thank you for the investigation

**Comment by carlescufi** [comment]
> @gschizas can you please rebase this PR so that it only contains the two relevant commits and no merge commits please?

@gschizas can you please rebase?

**Comment by carlescufi** [comment]
> > @gschizas can you please rebase this PR so that it only contains the two relevant commits and no merge commits please?
> 
> @gschizas can you please rebase?

If you'd like we can do this for you. Thanks!

**Comment by gschizas** [comment]
> > > @gschizas can you please rebase this PR so that it only contains the two relevant commits and no merge commits please?
> > 
> > 
> > @gschizas can you please rebase?
> 
> If you'd like we can do this for you. Thanks!

I'm not sure how to do that, so yes please.

**Comment by carlescufi** [comment]
@gschizas done

**Review by stephanosio — APPROVED** [review]
LGTM

**Pull request merged**
