### PR TITLE
Support Python 3.13

### LINKED ISSUE #69: Add Support for Python 3.13
Python 3.13 is out, which means this project needs an update to support it. I gave it [the old college try](https://github.com/pmbarrett314/windows-curses), but ran into [some snags](https://github.com/pmbarrett314/windows-curses/actions/runs/11338298421/job/31531276743) I don't have the bandwidth for. Creating an issue if anyone wants to point out anything glaring I've done wrong, or failing that just to track the status of support for the new version of Python.

### LINKED ISSUE #70: No matching distribution found for windows-curses
I get this error while installing:

```powershell
pwsh> pip install --upgrade windows-curses

ERROR: Could not find a version that satisfies the requirement windows-curses (from versions: none)
ERROR: No matching distribution found for windows-curses
```
```[tasklist]
### Tasks
- [ ] https://github.com/zephyrproject-rtos/windows-curses/issues/69
```

### PR DESCRIPTION
**Pull request by pmbarrett314**
Added support for Python 3.13. Seems to be working on my machine for all of the example files and my examples, but more testing is probably in order.

I followed all of the steps outlined in the readme, as well as making some additional modifications to deal with a couple of functions used in this library that cpython moved into private headers. It looks a little jank to me, but it is functional.

closes #69 
closes #70

### CODE REVIEW

**Comment by shvmm** [comment]
How do I download the corresponding wheels manually?
I just want to install this package

**Review by carlescufi — APPROVED** [review]
LGTM, thank you!

**Review by pdgendt — APPROVED** [review]

**Comment by carlescufi** [comment]
@pmbarrett314 thanks very much for your contribution. Hopefully @stephanosio will be able to test, merge and deploy soon.

**Comment by stephanosio** [comment]
Rebased on main

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
v2.4.1a1 has been released with the changes in this PR.

**Pull request merged**
